import defaultConfig from "tailwindcss/defaultConfig";
/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  safelist: [
    // "bg-neutral-100",
    // "bg-neutral-200",
    // "bg-neutral-300",
    // "bg-neutral-400",
    // "bg-neutral-500",
    // "bg-neutral-600",
    // "bg-neutral-700",
    // "bg-neutral-800",
    // "bg-neutral-900",
    // "bg-neutral-950",
    // "text-neutral-100",
    // "text-neutral-200",
    // "text-neutral-300",
    // "text-neutral-400",
    // "text-neutral-500",
    // "text-neutral-600",
    // "text-neutral-700",
    // "text-neutral-800",
    // "text-neutral-900",
    // "text-neutral-950",
    // "bg-blue-100",
    // "bg-blue-200",
    // "bg-blue-300",
    // "bg-blue-400",
    // "bg-blue-500",
    // "bg-blue-600",
    // "bg-blue-700",
    // "bg-blue-800",
    // "bg-blue-900",
    // "bg-blue-950",
    // "text-blue-100",
    // "text-blue-200",
    // "text-blue-300",
    // "text-blue-400",
    // "text-blue-500",
    // "text-blue-600",
    // "text-blue-700",
    // "text-blue-800",
    // "text-blue-900",
    // "text-blue-950",
    // "border-neutral-100",
    // "border-neutral-200",
    // "border-neutral-300",
    // "border-neutral-400",
    // "border-neutral-500",
    // "border-neutral-600",
    // "border-neutral-700",
    // "border-neutral-800",
    // "border-neutral-900",
    // "border-neutral-950",
    // "outline-black",
  ],
  theme: {
    container: {
      padding: "0 2rem",
      center: true,
    },
    extend: {
      fontFamily: {
        title: defaultConfig.theme.fontFamily.sans,
        body: defaultConfig.theme.fontFamily.sans,
      },
      colors: (theme) => ({
        background: {
          DEFAULT: theme.colors.neutral[100],
          2: theme.colors.neutral[200],
          3: theme.colors.neutral[300],
        },

        text: {
          DEFAULT: theme.colors.neutral[800],
          2: theme.colors.neutral[900],
          3: theme.colors.neutral[950],
          subtle: theme.colors.neutral[700],
        },

        border: {
          DEFAULT: theme.colors.neutral[800],
          2: theme.colors.neutral[900],
          3: theme.colors.neutral[950],
          subtle: theme.colors.neutral[700],
        },

        accent: {
          DEFAULT: theme.colors.blue[500],
          2: theme.colors.blue[600],
          3: theme.colors.blue[700],
          foreground: theme.colors.neutral[100],
        },

        "focus-ring": "black",
      }),
    },
  },
  plugins: [],
};
